### ISSUE TITLE
Document and AltGr are inverted

### ISSUE THREAD

**Issue by Dadoum** [asafscode/HP-Probook-430-G5-Hackintosh#1]
AltGr (Option key modifier) is inverted with Document (keyboard right click) key.

**Comment by asafscode** [comment]
*checks dsdt*

**Comment by asafscode** [comment]
that's how it is on this keyboard, that is also the macbook keyboard layout. if you don't like it you'll probably be able to remap keys with DSDT changes

**Comment by asafscode** [comment]
Hmmmm... the SSDT doesn't have anything related to the keyboard so this is probably a kext bug.
