### ISSUE TITLE
EFI/OC/TOOLS ISSUE!?!?!

### ISSUE THREAD

**Issue by AbdullahAhmed-hackintosh** [asafscode/HP-Probook-430-G5-Hackintosh#10]
Hi, why do you have the following tools?!?!?:

CleanNvram.efi
HdaCodecDump.efi
VerifyMsrE2.efi

These Tools are Completely Unnecessary and is just gonna make the thing boot up slower?!?!?!

Fix this plz!

**Comment by asafscode** [comment]
No.
