### ISSUE TITLE
Memory Panic Stackshot Succeeded (10.15.6)

### ISSUE THREAD

**Issue by johncodeos** [asafscode/HP-Probook-430-G5-Hackintosh#2]
Hi,
I added my SMBIOS (Tested with MackBookPro 11,1 and 15,2), and when I'm booting I'm getting:

** In Memory Panic Stackshot Succeeded **

![IMG_0768](https://user-images.githubusercontent.com/11445928/89409423-b6946c00-d72a-11ea-842f-9935937e0462.jpeg)

**Comment by asafscode** [comment]
Remove AppleAHCIPort.kext, this kext is actually a workaround for broken SATA on Big Sur but it panics on Catalina. You will need it on Big Sur.

**Comment by asafscode** [comment]
btw i'll soon push an update for big sur b4

**Comment by johncodeos** [comment]
> Remove AppleAHCIPort.kext, this kext is actually a workaround for broken SATA on Big Sur but it panics on Catalina. You will need it on Big Sur.

Yep! That was the problem!
I removed the **AppleAHCIPort.kext** and from the **config.plist** and now it's working!

Thanks!!

**Comment by johncodeos** [comment]
Hey, I'm reopening this because I have again a 'Memory Panic Stackshot Succeeded' with the latest release.
Here's the error:
![C7F46FAC-0DE6-44A9-A023-0B45391C43C0_1_105_c](https://user-images.githubusercontent.com/11445928/94932291-8d494f80-04d1-11eb-9527-2fd72180dbf0.jpeg)


I removed the **AppleAHCIPort.kext** too as you said.

**Comment by asafscode** [comment]
Try removing RMISMBus.kext from inside the VoodooRMI.kext plugins folder, I don't know if this is going to help, I run big sur on my machine.

**Comment by johncodeos** [comment]
Ok, I'll try it. 
Here's a better photo of the problem:
![79333286-59C3-452E-87B3-A84D015CC8F6_1_105_c](https://user-images.githubusercontent.com/11445928/94942963-b07afb80-04df-11eb-880f-494b8bb21f1d.jpeg)

**Comment by johncodeos** [comment]
> Try removing RMISMBus.kext from inside the VoodooRMI.kext plugins folder, I don't know if this is going to help, I run big sur on my machine.

Nah, It's not working. It gives me the same error as above. I'll try with an older commit of the repo

**Comment by johncodeos** [comment]
@asafscode What settings do I need to have in BIOS?

**Comment by asafscode** [comment]
pretty much the default ones, i don't know what's causing your error because i don't use catalina here. also applebacklightfixup is dead, use the SSDT

**Comment by asafscode** [comment]
for now use an older commit

**Comment by johncodeos** [comment]
Probably I'm gonna switch to Big Sur...

Thanks!
