### ISSUE TITLE
No sound after copying kexts from the 'LE' folder

### ISSUE THREAD

**Issue by johncodeos** [asafscode/HP-Probook-430-G5-Hackintosh#4]
After I copied the kext files from the 'LE' folder and did `sudo touch /Library/Extensions && sudo kextcache -i /`
Now the sound is not working at all (No speakers, no USB headphones, no headphones with audiojack).
Before copying them, everything was working without a problem (I didn't test the headphone jack)

Do I need to do something else after that?

**Comment by asafscode** [comment]
Don't use that kext, use layout id 21 instead. This will be the default in an update i'll make later today.

**Comment by asafscode** [comment]
I guess it's solved?
