### ISSUE TITLE
Need to plug-out and plug-in the HDMI cable every time you boot

### ISSUE THREAD

**Issue by johncodeos** [asafscode/HP-Probook-430-G5-Hackintosh#5]
I found that I need to plug-out and plug-in the HDMI cable every time the system is booting.

Using Clover didn't have this problem.

I remember RehabMan made a kext to fix this. Maybe is the **FakePCIID_Intel_HDMI_Audio.kext**

**Comment by asafscode** [comment]
If you send your entire clover config here i might be able to know why

**Comment by johncodeos** [comment]
Yeah, sure. [Here](https://github.com/johncodeos-repos/HP-Probook-440-G5-Clover)

**Comment by asafscode** [comment]
Fixed in the latest commit by adding `igfxonln=1` to boot-args
