### ISSUE TITLE
Won't boot on recent BIOS versions

### ISSUE THREAD

**Issue by Dadoum** [asafscode/HP-Probook-430-G5-Hackintosh#6]
I tried on Big Sur and latest Catalina and it will just get stuck on BuildActDeviceEntry exit in verbose or in the end of the progress bar.

Maybe due to BIOS Settings ? Can you communicate them ?

![image](https://user-images.githubusercontent.com/24679280/98578395-97732080-22bd-11eb-9daa-25b128bb5707.jpeg)

Edit: I try to boot installer

**Comment by asafscode** [comment]
First of all try with the latest update (I didn't have time to push it until now), another thing, if you are trying to boot the installer from an internal disk and not USB there might be some issues with that, to solve them you can use a the AppleAHCIPort.kext from older commits.

**Comment by Dadoum** [comment]
I put the master in a small partition in my usb drive, now, AppleAHCI just
makes everything panic, and without it, it does not write anything in the
verbose mode past « BuildActDeviceEntry exit »

**Comment by Dadoum** [comment]
![image](https://user-images.githubusercontent.com/24679280/98670340-de5f2580-2352-11eb-9c45-ff0b441755f9.jpeg)

**Comment by asafscode** [comment]
The AHCI kext panics catalina but on big sur it should work, also did you put an SMBIOS in config.plist?

**Comment by Dadoum** [comment]
I remade installer from macOS. I now boot from USB. In non verbose, it is
in the middle of the bar (maybe I should let it 1 hour ?) and in verbose it
does not write anything after the BuildActDeviceEntry exit. I am now
booting from USB key, on installer on USB key

**Comment by Dadoum** [comment]
(There is SMBIOS and the kext (folder+config), installer is latest Big Sur beta (developer))

**Comment by asafscode** [comment]
Well, i have no idea what’s going here, maybe BIOS revision differences? My BIOS is really old on this thing.
Anyways, try USBInjectAll maybe

**Comment by Dadoum** [comment]
Could be the issue since I updated recently my bios (due to a new feature).

**Comment by Dadoum** [comment]
Got no luck with USBInjectAll. Still in the middle of progress bar.

**Comment by asafscode** [comment]
On your BIOS, make sure to use a UEFI option ROM for everything

**Comment by Dadoum** [comment]
I see an option for « ROM Management Policy » UEFI for all. I set it  and
got no luck either

**Comment by Dadoum** [comment]
Which bios version do you have ? I will surely downgrade mine

**Comment by Dadoum** [comment]
Downgraded bios to 1.0 fixed my issue

**Comment by asafscode** [comment]
My BIOS is 01.01.07 10/17/2017

Well, issue closed since i’m not going to update my BIOS and fix this, everyone can downgrade anyways and “secure boot” is a fucked up thing on PCs so why not downgrade.
