### ISSUE TITLE
What Configuration and specs are your HP Probook 430 G5?

### ISSUE THREAD

**Issue by AbdullahAhmed-hackintosh** [asafscode/HP-Probook-430-G5-Hackintosh#7]
Hi, what are the specs of your What Configuration and specs are your HP Probook 430 G5?

**Comment by asafscode** [comment]
i5-8250U, 16GB of RAM (came with 8, I upgraded) and no touchscreen. Sorry for the late reply!

**Comment by AbdullahAhmed-hackintosh** [comment]
Hi, Thanks for response! Are you still having that BIOS Issue you mentioned?

**Comment by asafscode** [comment]
No, my BIOS is older so I don't have to deal with that.
