### ISSUE TITLE
BIOS Updates

### ISSUE THREAD

**Issue by AbdullahAhmed-hackintosh** [asafscode/HP-Probook-430-G5-Hackintosh#8]
Hi, Sorry to bother you! but for me (with your EFI) have managed to get macOS and Opencore to work Flawlessly with the latest BIOS (The One that came out November 2020 (Version: 1.14.1 Rev.A). I Think the problem is that after you Update your BIOS, the Default BIOS Settings Get implemented!. So After the update, go into your BIOS and change everything back to the settings to run macOS and Opencore Properly!

Thanks!

And Also remove that BIOS issue that you pointed out in README.md

**Comment by asafscode** [comment]
It works on my machine != it works on your machine
