### ISSUE TITLE
Add a Kext

### ISSUE THREAD

**Issue by AbdullahAhmed-hackintosh** [asafscode/HP-Probook-430-G5-Hackintosh#9]
Hi, 

I Noticed that in your EFI, you forgot to add the 'notouchid.kext' File. This Kext stops authentification issues on SMBIOS's that normally have Touch Built In (Like the 2018 Macbook Pro or macbookpro15,2). An Example of this is apps like LastPass which can error out as it thinks your 'macbook' has touch but does not. Thank You

https://github.com/al3xtjames/NoTouchID

Note: This issue appears to have been fixed on 10.15.7 and 11.0.1. This kext is unnecessary on these versions of macOS.

So for those who are running from macOS 10.13.4 to 10.15.7, They will need this kext!

Configuration
Add -nobiooff to disable NoTouchID
Add -nobiobeta to enable NoTouchID on unsupported OS versions (10.13-10.15 are supported by default)

**Comment by asafscode** [comment]
Anyone can add this themselves, this EFI is targeting Big Sur because that's what I run on my machine.
